// src/app/(auth)/login/page.tsx
"use client";

import { useState } from "react";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

export default function LoginPage() {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  const handleEmailLogin = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    setError("");
    try {
      // Supabase auth would go here
      window.location.href = "/feed";
    } catch {
      setError("Login failed");
    } finally {
      setLoading(false);
    }
  };

  const handleGoogleLogin = async () => {
    // Supabase Google OAuth would go here
    window.location.href = "/feed";
  };

  return (
    <div className="min-h-screen flex items-center justify-center p-4 bg-atlas-bg-primary">
      <div className="w-full max-w-sm">
        <div className="text-center mb-8">
          <h1 className="font-display text-3xl font-bold text-atlas-accent-emerald mb-2">Atlas</h1>
          <p className="text-sm text-atlas-text-secondary">Your personal intelligence feed</p>
        </div>

        <div className="bg-atlas-bg-secondary border border-atlas-border rounded-xl p-6">
          <Button
            variant="secondary"
            className="w-full mb-4"
            onClick={handleGoogleLogin}
          >
            Continue with Google
          </Button>

          <div className="flex items-center gap-3 my-4">
            <div className="flex-1 h-px bg-atlas-border" />
            <span className="text-xs text-atlas-text-muted">or</span>
            <div className="flex-1 h-px bg-atlas-border" />
          </div>

          <form onSubmit={handleEmailLogin} className="space-y-3">
            <Input
              label="Email"
              type="email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              placeholder="you@example.com"
              required
            />
            <Input
              label="Password"
              type="password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              placeholder="••••••••"
              required
            />
            {error && <p className="text-xs text-red-400">{error}</p>}
            <Button type="submit" className="w-full" disabled={loading}>
              {loading ? "Signing in..." : "Sign In"}
            </Button>
          </form>

          <p className="text-xs text-atlas-text-muted text-center mt-4">
            Don&apos;t have an account?{" "}
            <Link href="/signup" className="text-atlas-accent-sky hover:underline">
              Sign up
            </Link>
          </p>
        </div>

        <p className="text-xs text-atlas-text-muted text-center mt-4">
          Atlas works without an account —{" "}
          <Link href="/feed" className="text-atlas-accent-emerald hover:underline">
            continue as guest
          </Link>
        </p>
      </div>
    </div>
  );
}

// src/routes/(auth)/login/+page.svelte
<script lang="ts">
	import { loginWithGoogle, auth } from '$lib/auth/firebase';
	import { signInWithEmailAndPassword } from 'firebase/auth';
	import { goto } from '$app/navigation';

	let email = $state('');
	let password = $state('');
	let errorMessage = $state('');
	let isSubmitting = $state(false);

	async function handleEmailLogin(e: SubmitEvent) {
		e.preventDefault();
		if (!email || !password) {
			errorMessage = "Please enter both email and password.";
			return;
		}
		errorMessage = "";
		isSubmitting = true;
		try {
			await signInWithEmailAndPassword(auth, email, password);
			goto('/');
		} catch (error: any) {
			console.error(error);
			if (error.code === 'auth/invalid-credential') {
				errorMessage = "Invalid email or password. Please try again.";
			} else {
				errorMessage = error.message || "An authentication error occurred.";
			}
		} finally {
			isSubmitting = false;
		}
	}

	async function handleGoogleLogin() {
		errorMessage = "";
		try {
			await loginWithGoogle();
			goto('/');
		} catch (error: any) {
			console.error(error);
			errorMessage = error.message || "Failed to log in with Google.";
		}
	}
</script>

<svelte:head>
	<title>Atlas — Log In</title>
</svelte:head>

<div class="flex-1 flex flex-col items-center justify-center p-6 bg-black min-h-[80vh]">
	<div class="w-full max-w-sm glass-card p-8 rounded-2xl border-white/10 relative overflow-hidden">
		<!-- Aesthetic background blur highlight -->
		<div class="absolute -top-12 -left-12 w-32 h-32 bg-cyber-emerald/10 blur-3xl rounded-full"></div>
		<div class="absolute -bottom-12 -right-12 w-32 h-32 bg-cyber-violet/10 blur-3xl rounded-full"></div>

		<!-- Title -->
		<div class="text-center mb-8 relative z-10">
			<h1 class="font-display font-extrabold text-3xl tracking-tight text-white mb-2">ATLAS</h1>
			<p class="text-xs text-neutral-400 font-sans tracking-wide">YOUR PERSONAL KNOWLEDGE OS</p>
		</div>

		<!-- Form -->
		<form onsubmit={handleEmailLogin} class="space-y-5 relative z-10">
			{#if errorMessage}
				<div class="p-3 text-xs bg-red-950/40 border border-red-500/30 text-red-400 rounded-lg text-center font-medium">
					{errorMessage}
				</div>
			{/if}

			<div class="space-y-1.5">
				<label for="email" class="block text-xs uppercase tracking-wider text-neutral-400 font-bold">Email Address</label>
				<input 
					type="email" 
					id="email" 
					bind:value={email}
					placeholder="name@company.com" 
					class="w-full px-4 py-3 rounded-lg bg-neutral-900/60 border border-white/10 text-white placeholder-neutral-500 text-sm focus:outline-none focus:border-cyber-emerald focus:ring-1 focus:ring-cyber-emerald transition-all"
					required
				/>
			</div>

			<div class="space-y-1.5">
				<label for="password" class="block text-xs uppercase tracking-wider text-neutral-400 font-bold">Password</label>
				<input 
					type="password" 
					id="password" 
					bind:value={password}
					placeholder="••••••••" 
					class="w-full px-4 py-3 rounded-lg bg-neutral-900/60 border border-white/10 text-white placeholder-neutral-500 text-sm focus:outline-none focus:border-cyber-emerald focus:ring-1 focus:ring-cyber-emerald transition-all"
					required
				/>
			</div>

			<button 
				type="submit" 
				disabled={isSubmitting}
				class="w-full py-3 rounded-lg bg-white text-black font-bold text-sm tracking-wide uppercase hover:bg-neutral-200 active:scale-[0.98] transition-all disabled:opacity-50"
			>
				{isSubmitting ? 'Authenticating...' : 'Sign In'}
			</button>
		</form>

		<!-- Divider -->
		<div class="relative flex py-5 items-center z-10">
			<div class="flex-grow border-t border-white/5"></div>
			<span class="flex-shrink mx-4 text-[10px] uppercase tracking-widest text-neutral-500 font-bold">OR</span>
			<div class="flex-grow border-t border-white/5"></div>
		</div>

		<!-- Social Logins -->
		<div class="space-y-3 relative z-10">
			<button 
				onclick={handleGoogleLogin}
				class="w-full py-3 rounded-lg bg-neutral-900/50 border border-white/10 text-white text-sm font-bold tracking-wide uppercase hover:bg-neutral-800 active:scale-[0.98] transition-all flex items-center justify-center gap-2"
			>
				<!-- Google Icon -->
				<svg class="w-4 h-4" viewBox="0 0 24 24">
					<path fill="currentColor" d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z"/>
					<path fill="currentColor" d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z"/>
					<path fill="currentColor" d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.06H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.94l2.85-2.22.81-.63z"/>
					<path fill="currentColor" d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.06l3.66 2.84c.87-2.6 3.3-4.52 6.16-4.52z"/>
				</svg>
				Continue with Google
			</button>
		</div>

		<div class="mt-6 text-center text-xs text-neutral-500 relative z-10 font-medium">
			Don't have an account? 
			<a href="/register" class="text-cyber-emerald hover:underline font-bold ml-1">Register here</a>
		</div>
	</div>
</div>
